# Generated by Django 5.2.3 on 2025-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
