# Generated by Django 5.2.3 on 2025-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_vote_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
