# Generated by Django 5.2.3 on 2025-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_changed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
