# Generated by Django 5.2.3 on 2025-08-13 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.CharField(blank=True, max_length=20)),
                ('hall', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('imported', 'Imported'), ('self_submitted', 'Self Submitted'), ('admin_added', 'Admin Added')], default='self_submitted', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_entry', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_exhibition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='accounts_ex_phone_n_9df9c3_idx'), models.Index(fields=['is_verified'], name='accounts_ex_is_veri_8fc5d2_idx')],
            },
        ),
    ]
