# Generated by Django 5.2.3 on 2025-07-29 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('position', 'user'), name='unique_candidate_per_position_per_user'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='program',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='year_of_study',
        ),
    ]
