# Generated by Django 5.2.3 on 2025-08-08 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_require_dues_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('vote_cast', 'Vote Cast'), ('vote_viewed', 'Vote Viewed'), ('election_created', 'Election Created'), ('election_updated', 'Election Updated'), ('election_deleted', 'Election Deleted'), ('candidate_added', 'Candidate Added'), ('candidate_removed', 'Candidate Removed'), ('results_generated', 'Results Generated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('admin_access', 'Admin Access'), ('data_export', 'Data Export')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('integrity_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ElectionSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_vote_encryption', models.BooleanField(default=True)),
                ('enable_digital_signatures', models.BooleanField(default=True)),
                ('enable_audit_logging', models.BooleanField(default=True)),
                ('enable_ip_verification', models.BooleanField(default=True)),
                ('max_votes_per_minute', models.IntegerField(default=5)),
                ('max_login_attempts', models.IntegerField(default=3)),
                ('require_two_factor_auth', models.BooleanField(default=False)),
                ('whitelist_ip_addresses', models.JSONField(blank=True, default=list)),
                ('log_all_access', models.BooleanField(default=True)),
                ('log_failed_attempts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('votes_cast', models.IntegerField(default=0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_candidate_per_voter',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='elections_v_voter_i_0cd041_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='elections_v_candida_96ee3a_idx',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AddField(
            model_name='vote',
            name='anonymous_voter_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='election_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='vote',
            name='encrypted_vote_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='integrity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='position_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='vote',
            name='signature_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election_id', 'timestamp'], name='elections_v_electio_1f3117_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['position_id', 'timestamp'], name='elections_v_positio_c8228b_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['anonymous_voter_token'], name='elections_v_anonymo_ca596d_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['timestamp'], name='elections_v_timesta_c5c5db_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('anonymous_voter_token', 'position_id'), name='unique_anonymous_vote_per_position'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electionsecurity',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to='elections.election'),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='elections_a_user_id_2762ca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='elections_a_action_cfcf27_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='elections_a_resourc_e855d3_idx'),
        ),
        migrations.AddIndex(
            model_name='votingsession',
            index=models.Index(fields=['user', 'election'], name='elections_v_user_id_9ff57f_idx'),
        ),
        migrations.AddIndex(
            model_name='votingsession',
            index=models.Index(fields=['session_start'], name='elections_v_session_d3ebdd_idx'),
        ),
        migrations.AddIndex(
            model_name='votingsession',
            index=models.Index(fields=['is_suspicious'], name='elections_v_is_susp_6732b4_idx'),
        ),
    ]
