# Generated by Django 5.2.3 on 2025-08-03 10:37

from django.db import migrations


def clean_test_data(apps, schema_editor):
    """
    Clean up any test data to prepare for UUID migration
    """
    Position = apps.get_model("elections", "Position")
    Candidate = apps.get_model("elections", "Candidate")
    Vote = apps.get_model("elections", "Vote")

    # Clear all votes, candidates, and positions
    # This is safe for development - you'll recreate test data
    Vote.objects.all().delete()
    Candidate.objects.all().delete()
    Position.objects.all().delete()


def reverse_clean(apps, schema_editor):
    """
    Cannot reverse data deletion
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_alter_election_require_dues_payment"),
    ]

    operations = [
        migrations.RunPython(clean_test_data, reverse_clean),
    ]
