# Generated by Django 5.2.3 on 2025-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_position_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/%Y/profile_pictures/'),
        ),
    ]
