# Generated by Django 5.2.3 on 2025-08-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_candidate_id'),
        ('elections', '0006_candidate_profile_picture'),
    ]

    operations = [
    ]
