# Generated by Django 5.2.3 on 2025-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_election_results_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
